spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      hibernate:
        SQL: TRACE
        type: TRACE
    com.amoabin.updateservice: DEBUG
    org.springframework.transaction: DEBUG

test:
  mock-database: true