token:
  refresh:
    interval: 10000


server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show_sql: true
        format_sql: true
        logging:
          level:
            org:
              hibernate:
                SQL: DEBUG
                type: TRACE
                descriptor:
                  sql:
                    BasicBinder: TRACE
  data:
    jpa:
      repository: DEBUG
  sql:
    init:
      schema-locations: classpath:user_management

org:
  springframework:
    transaction: DEBUG

com:
  amoabin:
    updateservice: DEBUG


kubernetes:
  namespace: default