spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
    com.amoabin.updateservice: DEBUG
    org.springframework.transaction: DEBUG