token:
  refresh:
    interval: 10000

server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  sql:
    init:
      schema-locations: classpath:user_management

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
        descriptor:
          sql:
            BasicBinder: TRACE
    com.amoabin.updateservice: DEBUG
    org.springframework.transaction: DEBUG

kubernetes:
  namespace: default