CREATE SCHEMA IF NOT EXISTS user_management;

CREATE TABLE IF NOT EXISTS user_management.indicator_values (
                                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Auto-incrementing primary key
                                                account_classification VARCHAR(255) NOT NULL UNIQUE,     -- Unique account classification
                                                unique_id VARCHAR(36) NOT NULL UNIQUE,                   -- Unique column for UUID
                                                indicator CLOB DEFAULT NULL                              -- JSON-like column
);