apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-microservice
  namespace: dev # Namespace explicitly declared for clarity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-microservice
  template:
    metadata:
      labels:
        app: java-microservice
    spec:
      serviceAccountName: java-microservice-sa # ServiceAccount explicitly set at the spec level
      containers:
        - name: java-microservice
          image: 192.168.1.18:32000/update-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/mydatabase
            - name: SPRING_DATASOURCE_USERNAME
              value: myuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: mypassword
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            # Optional: Default profile for flexibility
            - name: SPRING_PROFILE_ACTIVE
              value: default
          ports:
            - containerPort: 8083
              protocol: TCP