apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-microservice
  namespace: dev
spec:
  template:
    spec:
      containers:
        - name: java-microservice
          env:
            - name: SPRING_PROFILE_ACTIVE
              value: dev