apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-microservice
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: java-microservice
          env:
            - name: SPRING_PROFILE_ACTIVE
              value: dev